source 'https://rubygems.org'

ruby '2.2.1'
gem 'rails', '4.1.8'
gem 'mongoid', '~> 4', github: 'mongoid/mongoid'
gem 'bson_ext'
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end
gem 'jquery-rails'
gem 'puma'
gem 'rails-i18n'
gem 'paperclip'
gem 'haml'
gem 'turbolinks'
gem 'therubyracer'
gem 'devise'
gem 'mongoid-paperclip', :require => 'mongoid_paperclip'
gem 'nokogiri'
gem 'video_info'
gem 'streamio-ffmpeg'
gem 'google-search'
gem 'mini_magick'
gem 'angular-ui-bootstrap-rails'